// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using AssemblyCSharp;

namespace Application
{
	public class NinjaRunState : AIState
	{
		Animator anim;
		GravitySprite grav;

		public override void doStart (GameObject g)
		{
			anim = g.GetComponent<Animator> ();
			grav = g.GetComponent<GravitySprite> ();

		}

		public override void doFixedUpdate()
		{
			grav.run (new Vector2 (1, 0));
		}
	}
}

