// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace Application
{
	public class GravitySprite : MonoBehaviour
	{
		bool isJumping = true; 
		Animator anim;
		Rigidbody2D rb;
		public float runVel = 1.41f;
				
		public void Start ()
		{
			anim = GetComponent<Animator> ();
			rb = GetComponent<Rigidbody2D> ();
		}

		public void Update()
		{
			anim.SetFloat ("Speed", Mathf.Abs( rb.velocity.x));

		}

		public void land()
		{
			if (anim.GetCurrentAnimatorStateInfo (0).IsName ("idle"))
				return;
			isJumping = false;
			anim.SetTrigger ("Land");
			anim.SetBool ("Jump", false);
		}

		public void jump()
		{
			if (isJumping) {
				return;
			}
			
			if (anim.GetCurrentAnimatorStateInfo (0).IsName ("jumping")) {
				return;
			}
			
			Debug.Log ("jumping!");
			rb.AddForce(new Vector2(0,200));
			isJumping = true;
			anim.SetTrigger("Jump");
			
			anim.SetBool ("Land", false);
		}

		public void run(Vector2 dir)
		{
			Vector2 vel = rb.velocity;
			vel.x = dir.x * runVel;
			rb.velocity = vel;
		}

	}
}

