// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
using AssemblyCSharp;

namespace Application
{
	public class DragonInitialState: AIState
	{
		Timer fireTimer;
		Dragon dragon;
		Rigidbody2D rb;

		public DragonInitialState  ()
		{
		}

		public override void doFixedUpdate()
		{
			rb.velocity = new Vector2 (0, 1);
		}

		public override void doStart(GameObject g)
		{
			dragon = GameObject.Find ("dragon").GetComponent<Dragon> ();
			rb = GameObject.Find ("dragon").GetComponent<Rigidbody2D> ();
		}

	}
}

