// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using AssemblyCSharp;

namespace Application
{
	public class DragonFireState: AIState
	{
		public DragonFireState  ()
		{
		}

		public override void doFixedUpdate()
		{

		}

		public override void Start()
		{

		}
	}
}

